### ISSUE TITLE
Crash on authorize (Android)

### ISSUE THREAD

**Issue by bulats** [FormidableLabs/react-native-app-auth#150]
Started getting this issue today without making any changes to my app. Tried it with the example app and the exact same issue persists. 

Basically the app crashes when I try to authorize.

The error message:

```
07-19 23:22:01.124 5294-5294/com.appauthexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appauthexample, PID: 5294
    android.content.ActivityNotFoundException
        at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:351)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:255)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:283)
        at com.reactlibrary.RNAppAuthModule.authorizeWithConfiguration(RNAppAuthModule.java:307)
        at com.reactlibrary.RNAppAuthModule.access$000(RNAppAuthModule.java:44)
        at com.reactlibrary.RNAppAuthModule$1.onFetchConfigurationCompleted(RNAppAuthModule.java:111)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:364)
        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(AuthorizationServiceConfiguration.java:305)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-19 23:22:01.131 590-590/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=5294 uid=10260 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
07-19 23:22:01.132 590-590/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=5294 uid=10260 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0

```
Any ideas?

**Comment by kadikraman** [comment]
Hi, I've just tried the latest Example app on a `Nexus 5X API 25` emulator through Android Studio and I couldn't reproduce the error. Can you reproduce it on multiple devices?

**Comment by bulats** [comment]
@kadikraman I've fixed the issue by doing a factory reset. Not sure what the problem was.

**Comment by ws7one** [comment]
@bulats a factory reset on what?
