### ISSUE TITLE
Running example got Failed to fecth configuration

### ISSUE THREAD

**Issue by ciptoj** [FormidableLabs/react-native-app-auth#170]
Hi,

I've set up an identityserver4 running in localhost and in HTTPS with self-signed trusted localhost cert.
I modify your Example project and no matter what I change I keep getting "Failed to Fetch Configuration"
Can you pinpoint what can go wrong?

**Comment by ciptoj** [comment]
const config = {
  issuer: 'https://localhost:5001',
  clientId: 'native.code',
  redirectUrl: 'mycallback://callback',
  additionalParameters: {},
  scopes: ['openid', 'profile', 'email', 'offline_access'],
  dangerouslyAllowInsecureHttpRequests:false
}

**Comment by ciptoj** [comment]
In the log of Identity server, it shows the exception message:
Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)

**Comment by ciptoj** [comment]
I make some progress, I specify explicitely the serverconfiguration.
but now this error comes up
![image](https://user-images.githubusercontent.com/8856652/45147656-a64a7e00-b1ef-11e8-8d7f-96195a9489ec.png)

**Comment by kadikraman** [comment]
Hi, it looks like you aren't able to access your localhost from your emulator.

To test this, try going to https://localhost:5001/.well-known/openid-configuration in your browser first on your PC and then in the Android emulator. You should be able to see a JSON configuration file.
