### ISSUE TITLE
Failed to fetch configuration

### ISSUE THREAD

**Issue by YuraSrohiy** [FormidableLabs/react-native-app-auth#21]
Hi!
I'm trying to make uber oauth2 work but I keep getting this error (currently testing on android).
```
Error: Failed to fetch configuration
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:346)
    at MessageQueue.js:132
    at MessageQueue.__guard (MessageQueue.js:262)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:131)
    at debuggerWorker.js:72
```

From what I've seen in issues, this is a problem with 'issuer' variable. Seems like I can't understand what string I should use there.

Here is my code

```  
    const scopes = ["request"];
    const appAuth = new AppAuth({
      issuer: "https://login.uber.com/oauth/v2/authorize",
      clientId: settings.UberClientId,
      redirectUrl: "myApp:/oauth"
    })

    appAuth.authorize(scopes).then((response)=>{
      console.log('response=>', response)
    }).catch((reject)=>{
      console.log('reject=>', reject)
    });
```

Here is the screenshot of uber endpoints
![image](https://user-images.githubusercontent.com/12134512/35730243-fb81a6bc-0819-11e8-9f79-5d2837bd46d2.png)

**Comment by kadikraman** [comment]
Hi @YuraSrohiy - neither of these would work unfortunately. This library is built specifically for communicating with OAuth 2.0 and OpenID Connect providers, however Uber does not do OpenID.

**Comment by kadikraman** [comment]
Hi @YuraSrohiy - I imagine you've found an alternate solution now, however, just to let you know, we've just released a new [version](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v2.2.0) that supports custom configurations. This incidentally now means that it supports authentication with Uber, yay 🌟 

Documentation can be found [here](https://github.com/FormidableLabs/react-native-app-auth#uber).

**Comment by ws7one** [comment]
```
const config = {
            issuer: 'https://demo.identityserver.io',
            clientId: 'native.code',
            redirectUrl: 'io.identityserver.demo:/oauthredirect',
            scopes: ['openid', 'profile', 'offline_access']
        };

        try {
            const result = await authorize(config);
            console.log(result);
            // result includes accessToken, accessTokenExpirationDate and refreshToken
        } catch (error) {
            console.log(error);
        }
```

I am facing the same issue with the above code. I got the following error. Not sure what am I doing wrong

```
Error: Failed to fetch configuration
    at createErrorFromErrorData (D:\ReactNative\AlphaM\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:146)
    at D:\ReactNative\AlphaM\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:95
    at MessageQueue.__invokeCallback (D:\ReactNative\AlphaM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:397)
    at D:\ReactNative\AlphaM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:127
    at MessageQueue.__guard (D:\ReactNative\AlphaM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (D:\ReactNative\AlphaM\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:126)
    at debuggerWorker.js:72
```

**Comment by kadikraman** [comment]
Hmm, how exactly are you getting this error? Are you running one of the demo apps? What's your environment like? Mac/Linux/Windows Android/iOS?

**Comment by ws7one** [comment]
@kadikraman
I am not running a demo app. This is a login page I have to implement using Identity 4. All I did was followed the steps to setup rn app auth, and added a button, on click of which the following code runs

```
 onLoginPress = async () => {
        // this.props.loginUser(this.props.signIn.username, this.props.signIn.password);
        console.log('Login');
        const config = {
            issuer: 'http://demo.identityserver.io',
            clientId: 'native.code',
            redirectUrl: 'io.identityserver.demo:/oauthredirect',
            scopes: ['openid', 'profile', 'offline_access']
        };
        try {
            const result = await authorize(config);
            console.log(result);
            // result includes accessToken, accessTokenExpirationDate and refreshToken
        } catch (error) {
            console.log(error);
        }
    }
```

I am running this on a Windows machine in a Android emulator

**Comment by ws7one** [comment]
I just restarted my windows machine, created a new emulator on Android, ran the same app and the App crashed. Not sure why, but I did not get the error i was getting before. This seems like #150 
The solution there was a factory reset, where should I be doing a factory reset exactly? @kadikraman

**Comment by kadikraman** [comment]
@ws7one does your emulator have internet access? As in, can you open a browser in the emulator and go to https://demo.identityserver.io/.well-known/openid-configuration ?

**Comment by ws7one** [comment]
yes i can.. though it seems to be ignoring the https part.. But I can see the config @kadikraman

**Comment by kadikraman** [comment]
What happens when you specify the configuration manually?

```
{
  clientId: 'native.code',
  redirectUrl: 'io.identityserver.demo:/oauthredirect',
  additionalParameters: {},
  scopes: ['openid', 'profile', 'email', 'offline_access'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://demo.identityserver.io/connect/authorize',
    tokenEndpoint: 'https://demo.identityserver.io/connect/token',
    revocationEndpoint: 'https://demo.identityserver.io/connect/revoke'
  }
}
```

**Comment by ws7one** [comment]
😮 @kadikraman 😮 
What just happened? How did this work?
This worked perfectly, while i tried the previous config and it crashes the app.
How? Why? What? 😮

**Comment by kadikraman** [comment]
@ws7one the two configs are functionally equivalent. The former is a convenience for IDPs that support openID (so we can fetch the necessary endpoints from `<issuer>/.well-known/openid-configuration`)

For some reason you're getting an SSL error when requesting the configuration endpoint on the device. I've no idea why, I can't reproduce it.

**Comment by ws7one** [comment]
@kadikraman I am still very new to Identity Server and OAuth and OpenID and the whole world of SSO. Can you help me with this.

I have the following as one of the client in my server.
```
{
				"IsActive": true,
				"ClientName": "MobileNewsHybridDev",
				"ClientId": "MobileNewsHybridDev",
				"AllowedGrantType": [ "client_credentials", "hybrid" ],
				"RequireConsent": false,
				"ClientSecrets": [
					"secret"
				],
				"RedirectUris": [
					"io.identityserver.demo:/oauthredirect"
				],
				"PostLogoutRedirectUris": [
					"http://io.identityserver.demo:/"
				],
				"AllowedScopes": [
					"openid",
					"profile",
					"newsAPI"
				],
				"AllowOfflineAccess": true,
				"AllowAccessTokensViaBrowser": true,
				"IdentityTokenLifetime" : 21600,
				"AccessTokenLifetime" : 21600
			},
```

I used the same config that you gave and replaced the values appropriately as follows:
```
const config = {
            clientId: 'MobileNewsHybridDev',
            redirectUrl: 'io.identityserver.demo:/oauthredirect',
            additionalParameters: {},
            scopes: ['openid', 'profile', 'newsAPI', 'offline_access'],
            serviceConfiguration: {
                authorizationEndpoint: 'http://auth.heckyl.com/connect/authorize',
                tokenEndpoint: 'http://auth.heckyl.com/connect/token',
                revocationEndpoint: 'http://auth.heckyl.com/connect/revoke'
            },
        };
```

I am guessing the redirectUrl can be the same, later i will have to replace `io.identityserver.demo` with something else and make the same change in the gradle file

For now i am getting error in my logs as below: 
```
Invalid grant type for client: authorization_code
{
        "ClientId": "MobileNewsHybridDev",
        "ClientName": "MobileNewsHybridDev",
        "RedirectUri": "io.identityserver.demo:/oauthredirect",
        "AllowedRedirectUris": [
          "io.identityserver.demo:/oauthredirect"
        ],
        "SubjectId": "anonymous",
        "ResponseType": "code",
        "ResponseMode": "query",
        "GrantType": "authorization_code",
        "RequestedScopes": "",
        "State": "Q3AqVb0TjQJ4FJ86g3toDg",
        "Raw": {
          "redirect_uri": "io.identityserver.demo:/oauthredirect",
          "client_id": "MobileNewsHybridDev",
          "response_type": "code",
          "state": "Q3AqVb0TjQJ4FJ86g3toDg",
          "scope": "openid profile newsAPI offline_access",
          "code_challenge": "iY6nqsznWyVue-lOkEXJkEosDn4ZgW09G-0lNL4tapY",
          "code_challenge_method": "S256"
        }
      }
```

the request gone thru is this 
`http://auth.heckyl.com/connect/authorize?redirect_uri=io.identityserver.demo%3A%2Foauthredirect&client_id=MobileNewsHybridDev&response_type=code&state=Q3AqVb0TjQJ4FJ86g3toDg&scope=openid%20profile%20newsAPI%20offline_access&code_challenge=iY6nqsznWyVue-lOkEXJkEosDn4ZgW09G-0lNL4tapY&code_challenge_method=S256  `

I can see that there is an error regarding 'grant type' which is not mentioned in the config that we sent. How do we mention what grant type we have to send?

**Comment by kadikraman** [comment]
@ws7one have you checked out the IdentityServer demo configuration? You'll want to follow the example with PKCE for mobile. That's what the demo app is using. The code definition is available [here](https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Config.cs#L67)

**Comment by ws7one** [comment]
@kadikraman thanks for the link. 

I got the client config right, and was able to get to the login page on our identity server
I entered the creds correctly and pressed login, but after than it did not redirect back to the app. 

I am sure the redirect uri got fired, cos the app opened for a second and crashed. 
Now when i open the app again and I try to reach the identity server to authorize, the app crashes but there too for a second, the chrome tab opens and closes and the app crashes. 

I checked the logs on the server end, and it seems the user did get authenticated.

Seems like there is an issue when the redirecturi is called since the app crashed after the user is authenticated. and on relaunching the app, it seems that since the user is already authenticated, it tries to fire the redirecturi and the app crashes again.

This is still just something I think is the point when the app is crashing, i cant be sure.
I need to get this working by today.
Can you please help?

**Comment by kadikraman** [comment]
Add
```
additionalParameters: {
  prompt: "login"
}
```
if you want the user to enter their credentials every time.

As for the crash, run the app in debug mode from Android Studio, or run `react-native log-android` to hook into the logs. Check if your redirect scheme is set correctly - that's the most likely cause.

**Comment by ws7one** [comment]
@kadikraman 

```
additionalParameters: {
  prompt: "login"
}
```

this worked properly, this made sure the user is logging in everytime, but still the redirecturl when fired closes the app.. The redirect url works fine when working with the demo example that we tried before, and I am sure `io.identityserver.demo:/oauthredirect` will work fine here too unless '/oauthdirect' means something else and that needs to be changed too. So iam really not sure whats going wrong where. 

I am not sure how to run a react native app through android studio and `react-native log-android` didnt really help, it did not give any logs before the app crashes

**Comment by kadikraman** [comment]
I don't know if it's different on Windows, but on Mac, you can just open your project in Android Studio (it's got emulator support built, though you have to install an emulator before you can use it) and just run the app in debug mode. That will allow you to see all the native logs, including stack trace for any fatal errors.

**Comment by ws7one** [comment]
```
2018-11-16 18:22:37.347 2032-3082/system_process I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=io.identityserver.demo:/oauthredirect?code=852eb43ac6bd1df3ba515ec607d5d413b79132d20ae7a0f3bc3bd1832b40e16c&scope=openid profile newsAPI&state=DTIl1g4BCehjFcUROi25YQ&session_state=L7jIKLxuUpcjYGsUefvlXg69wnENhVWwMPJsouqEFLQ.3c6fb75ce17f5c4f81f1599b347fa9ef flg=0x14000000 cmp=com.alpham/net.openid.appauth.RedirectUriReceiverActivity (has extras)} from uid 10065
2018-11-16 18:22:37.429 6129-6129/com.alpham W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@770086b
2018-11-16 18:22:37.469 2032-3082/system_process I/ActivityManager: START u0 {dat=io.identityserver.demo:/oauthredirect?code=852eb43ac6bd1df3ba515ec607d5d413b79132d20ae7a0f3bc3bd1832b40e16c&scope=openid profile newsAPI&state=DTIl1g4BCehjFcUROi25YQ&session_state=L7jIKLxuUpcjYGsUefvlXg69wnENhVWwMPJsouqEFLQ.3c6fb75ce17f5c4f81f1599b347fa9ef flg=0x24000000 cmp=com.alpham/net.openid.appauth.AuthorizationManagementActivity} from uid 10085
2018-11-16 18:22:37.498 2032-3082/system_process W/ActivityManager: Duplicate finish request for ActivityRecord{dd7840 u0 com.alpham/net.openid.appauth.RedirectUriReceiverActivity t11 f}
2018-11-16 18:22:38.090 6129-6156/com.alpham D/EGL_emulation: eglMakeCurrent: 0xdef1a260: ver 2 0 (tinfo 0xce0a7400)
2018-11-16 18:22:38.877 6129-6271/com.alpham E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: com.alpham, PID: 6129
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: only https connections are permitted
        at net.openid.appauth.Preconditions.checkArgument(Preconditions.java:116)
        at net.openid.appauth.connectivity.DefaultConnectionBuilder.openConnection(DefaultConnectionBuilder.java:51)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:418)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:395)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2018-11-16 18:22:38.922 2032-2848/system_process W/ActivityManager:   Force finishing activity com.alpham/.MainActivity
2018-11-16 18:22:38.960 6129-6271/com.alpham I/Process: Sending signal. PID: 6129 SIG: 9
2018-11-16 18:22:39.065 2032-2144/system_process W/InputDispatcher: channel '4c499c3 com.alpham/com.alpham.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2018-11-16 18:22:39.065 2032-2144/system_process E/InputDispatcher: channel '4c499c3 com.alpham/com.alpham.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-11-16 18:22:39.071 2032-2144/system_process W/InputDispatcher: channel 'ea68ac1 com.alpham/net.openid.appauth.AuthorizationManagementActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2018-11-16 18:22:39.071 2032-2144/system_process E/InputDispatcher: channel 'ea68ac1 com.alpham/net.openid.appauth.AuthorizationManagementActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-11-16 18:22:39.110 2032-2044/system_process I/ActivityManager: Process com.alpham (pid 6129) has died: vis  +99TOP 
2018-11-16 18:22:39.123 2032-4727/system_process I/WindowManager: WIN DEATH: Window{4c499c3 u0 com.alpham/com.alpham.MainActivity}
2018-11-16 18:22:39.123 2032-4727/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '4c499c3 com.alpham/com.alpham.MainActivity (server)'
2018-11-16 18:22:39.138 2032-2301/system_process I/WindowManager: WIN DEATH: Window{ea68ac1 u0 com.alpham/net.openid.appauth.AuthorizationManagementActivity}
2018-11-16 18:22:39.138 2032-2301/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'ea68ac1 com.alpham/net.openid.appauth.AuthorizationManagementActivity (server)'
2018-11-16 18:22:39.513 1837-2148/? W/SurfaceFlinger: Attempting to set client state on removed layer: com.alpham/com.alpham.MainActivity#0
2018-11-16 18:22:39.513 1837-2148/? W/SurfaceFlinger: Attempting to destroy on removed layer: com.alpham/com.alpham.MainActivity#0
```

I got these logs on LogCat in android studio. I get this `FATAL EXCEPTION` here. Seems something is going on redirecturi

**Comment by kadikraman** [comment]
```
Caused by: java.lang.IllegalArgumentException: only https connections are permitted
```

Are you running your server on local host over http? If so, we have an option that allows it for local development: `dangerouslyAllowInsecureHttpRequests`.

**Comment by ws7one** [comment]
@kadikraman 
I realised later that it was http and not https, got that fixed and a couple of other changes fixed it for me. Thank you so much. My client config on the server looks like this now:
```
{
				"IsActive": true,
				"ClientId": "native.code",
				"ClientName": "Native Client (Code with PKCE)",
				"RedirectUris": [ 
					"io.identityserver.demo:/oauthredirect" 
				],
				"PostLogoutRedirectUris": [ 
					"io.identityserver.demo:/oauthredirect" 
				],
				"RequireClientSecret": false,
				"AllowedGrantType": [ "authorization_code" ],
				"RequirePkce": true,
				"RequireConsent": false,
				"AllowedScopes": [ 
					"openid", 
					"profile",
					"newsAPI"
				],
				"AllowOfflineAccess": true,
				"SetRefreshConfig": true,
				"RefreshTokenUsage": 0
			},
```

and the config for authorize looks as follows:

```
{
                clientId: 'native.code',
                redirectUrl: 'io.identityserver.demo:/oauthredirect',
                additionalParameters: { prompt: 'login' },
                scopes: ['openid', 'profile', 'newsAPI', 'offline_access'],
                serviceConfiguration: {
                    authorizationEndpoint: 'https://auth.heckyl.com/connect/authorize',
                    tokenEndpoint: 'https://auth.heckyl.com/connect/token',
                    revocationEndpoint: 'https://auth.heckyl.com/connect/revoke'
                },
            },
```

Authorize also works with: 
```
{
                issuer: 'https://auth.heckyl.com',
                clientId: 'native.code',
                redirectUrl: 'io.identityserver.demo:/oauthredirect',
                scopes: ['openid', 'profile', 'newsAPI', 'offline_access']
            },
```

Only not sure how to pass `{ prompt: 'login' }` to make the user login mandatorily.

The next issue right now I am facing is when I try to refresh the token I have recieved
```
const refreshedState = await refresh({
                    ...shortConfig,
                    refreshToken: refreshToken,
                }); 
```

I get the following error:
```
TypeError: Cannot read property 'refreshToken' of undefined
    at refresh (blob:http://localhost:8081/11dd7273-1c9d-4d86-976b-2461944b64d7:102203:30)
    at AuthLoadingScreen._callee2$ (blob:http://localhost:8081/11dd7273-1c9d-4d86-976b-2461944b64d7:101990:83)
    at tryCatch (blob:http://localhost:8081/11dd7273-1c9d-4d86-976b-2461944b64d7:20184:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/11dd7273-1c9d-4d86-976b-2461944b64d7:20359:24)
    at Generator.prototype.(anonymous function) [as next] (blob:http://localhost:8081/11dd7273-1c9d-4d86-976b-24
```

Not sure what am I doing wrong. I appreciate all the help you have done till now. Thank you so much, but I seem to be hitting a wall everytime new thing I try, well I am just a little clumsy that way. Could you please help me out with this too.

**Comment by ws7one** [comment]
@kadikraman 
Thanks so much, this works fine, though I did run into an error on the server, which i am looking into right now
`Refresh token cannot be found in store: fb5eed74fe5cc6da3c69e8da5d0d68ec912524b7beeb1f7209457b6296dfcbe3`

but i was trying the example given here in the link below:
[https://github.com/FormidableLabs/react-native-app-auth#identity-server-4](https://github.com/FormidableLabs/react-native-app-auth#identity-server-4)
How does this work then?

**Comment by frostless** [comment]
I had this problem once and the reason was my emulator had no internet connection
