### ISSUE TITLE
Authorization call can cause application to crash on Android

### ISSUE THREAD

**Issue by Vanclief** [FormidableLabs/react-native-app-auth#390]
## Issue

Just like [this issue](https://github.com/FormidableLabs/react-native-app-auth/issues/372) which was closed for using the rc version, my application is crashing after an `authorize` call. The steps are:

1. I call the authorize function
2. The browser is displayed, and I login with my credentials on OAuth
3. The application crashes and the authorize function doesn't return anything.

*Trace* 
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: only https connections are permitted
	at net.openid.appauth.Preconditions.checkArgument(Preconditions.java:116)
	at net.openid.appauth.connectivity.DefaultConnectionBuilder.openConnection(DefaultConnectionBuilder.java:51)
	at com.rnappauth.utils.CustomConnectionBuilder.openConnection(CustomConnectionBuilder.java:49)
	at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:418)
	at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:395)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```
---

## Environment

* **Your Identity Provider**: `ORY Hydra`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No
* **react-native-app-auth**: 4.4.0

---

As the error logs show, this issue is likely related to the OAuth provider not establishing a https connection, however these kind of issues should not cause the application to crash. Related to this one: https://github.com/FormidableLabs/react-native-app-auth/issues/385

**Comment by joelfsreis** [comment]
Hey, I'm also facing this issue on a release build. A Motorola device - Moto Z 2 - also crashes when calling the `authorize` method although it works fine for other Android devices.

Any suggestions on this one?

**Comment by canberkardic** [comment]
Same problem here

**Comment by Jay-A-McBee** [comment]
Note this error in the callstack 

> Caused by: java.lang.IllegalArgumentException: only https connections are permitted

Use`dangerouslyAllowInsecureHttpRequests: true` if your authentication request targets a remote resource that uses `http` protocol.

Closing this out.
