### ISSUE TITLE
App crashing when capturing redirect

### ISSUE THREAD

**Issue by souljacker** [FormidableLabs/react-native-app-auth#398]
## Issue

As soon as I authorize the app remotely, it crashes. My log at the moment shows the following:

`10-09 20:08:46.094 16187 16240 D EGL_emulation: eglMakeCurrent: 0xdeab23c0: ver 3 0 (tinfo 0xdeb1ce80)
10-09 20:08:46.111  2093  2126 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state: open failed: ENOENT (No such file or directory)
10-09 20:08:46.095 16187 16240 D EGL_emulation: eglMakeCurrent: 0xdeab23c0: ver 3 0 (tinfo 0xdeb1ce80)
10-09 20:08:46.116  2093  2123 I libprocessgroup: Successfully killed process cgroup uid 99154 pid 18121 in 44ms
10-09 20:08:46.531 18186 18217 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
10-09 20:08:46.531 18186 18217 E AndroidRuntime: Process: com.scpush, PID: 18186
10-09 20:08:46.531 18186 18217 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:399)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
10-09 20:08:46.531 18186 18217 E AndroidRuntime: Caused by: java.lang.NullPointerException
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.io.Reader.<init>(Reader.java:78)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at net.openid.appauth.Utils.readInputStream(Utils.java:36)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:453)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:395)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:378)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-09 20:08:46.531 18186 18217 E AndroidRuntime:        ... 4 more
10-09 20:08:46.536  2093  3101 W ActivityTaskManager:   Force finishing activity com.scpush/.MainActivity
10-09 20:08:46.537  2093 18333 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2`

Any idea on what's going on here?

---

## Environment

* **Your Identity Provider**: `custom`
* **Platform that you're experiencing the issue on**: `android`
* **Are you using Expo?** no

**Comment by kadikraman** [comment]
Hi @souljacker 👋 - I'm really not sure at this point. It could be a lot of things.

Could you try using the example configuration:

```
{
  issuer: 'https://demo.identityserver.io',
  clientId: 'native.code',
  redirectUrl: 'io.identityserver.demo:/oauthredirect',
  additionalParameters: {},
  scopes: ['openid', 'profile', 'email', 'offline_access']
}
```
And `io.identityserver.demo` as the `appAuthRedirectScheme` and see if this also errors?

**Comment by jsbeckr** [comment]
Hi @kadikraman,

it works as expected with your example configuration. 

But it crashes with the following configuration:

```typescript
let config: AuthConfiguration = {
  serviceConfiguration: {
    authorizationEndpoint: `${testUrl}/authorize`,
    tokenEndpoint: `${testUrl}/token`,
  },
  clientId: "R2dpxQ3vPrtfgF72",
  clientSecret: "fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9",
  redirectUrl: "com.test.myapp://oauth",
  scopes: ["profile"],
};
```

We are investigating it right now.

Do you have an idea? Thank you for your help.

**Comment by jsbeckr** [comment]
Removing `clientSecret` did the trick.
