### ISSUE TITLE
App crashes In Android all devices when tap on the home button and application goes to the background

### ISSUE THREAD

**Issue by 144ashok** [FormidableLabs/react-native-app-auth#422]
App crashes In Android all devices when tap on the home button and application goes to the background

When open my application click on login button then call the function authorize of react-native-app-auth then i able to see the OAuth server and then logged in to application successfully. But when i call the authorize method  open the OAuth server Login page, and not loged in to this, At that time if i pressed the phone home screen button and then application are running in the background and again tap on application icon try to open then below error i face and application crashes.
 please help to me.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobile, PID: 28749
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {com.mobile/com.mobile.MainActivity}: java.lang.NullPointerException: dataIntent must not be null
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4465)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4507)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1846)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6882)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: dataIntent must not be null
        at net.openid.appauth.Preconditions.checkNotNull(Preconditions.java:55)
        at net.openid.appauth.AuthorizationResponse.fromIntent(AuthorizationResponse.java:564)
        at com.rnappauth.RNAppAuthModule.onActivityResult(RNAppAuthModule.java:303)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:275)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:89)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:110)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:67)
        at android.app.Activity.dispatchActivityResult(Activity.java:7598)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4458)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4507) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1846) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6882) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
I/Process: Sending signal. PID: 28749 SIG: 9
Process 28749 terminated.

**Comment by kadikraman** [comment]
Hi 👋 - I was unable to reproduce this on `Pixel 3 API 29` `react-native-app-auth@5.0.0-rc4`

![no-crash](https://user-images.githubusercontent.com/6534400/71982409-4d905880-321c-11ea-9aea-5f177021d6b5.gif)

Please provide steps to reproduce if the issue persists.
