### ISSUE TITLE
[Android] App is getting crashed. allowInsecureConnections is null

### ISSUE THREAD

**Issue by tarun29061990** [FormidableLabs/react-native-app-auth#460]
## Issue

In createConnectionBuilder function allowInsecureConnections coming as null. Android app is getting crashed because of this. But if I try 2-3 times it works. Please help my app is getting crashed in production.
Stack trace:
```
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=com.livspace.canvas.android:///login?code=pZJYUn2Q4zJ3xQIngXEexFP5YHJ9NL87zFqih63csmk.wtJ4Ql6-2BTHJfZbWKs12YlF27Nqoq1uT2ViNFmQgjk&scope=openid offline offline_access&state=2JjhOtCB-80s4UfomoVIkQ (has extras) }} to activity {com.livspace.canvas.android/com.livspace.canvas.android.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4415)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4459)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1738)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6754)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.equals(java.lang.Object)' on a null object reference
        at com.rnappauth.RNAppAuthModule.createConnectionBuilder(RNAppAuthModule.java:538)
        at com.rnappauth.RNAppAuthModule.onActivityResult(RNAppAuthModule.java:317)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:277)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:704)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:129)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
        at android.app.Activity.dispatchActivityResult(Activity.java:7433)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4411)


```
---

## Environment

* **Your Identity Provider**: Hydra
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** No

**Comment by dcenatiempo** [comment]
Same issue - same stacktrace. This is for v4.4. We are going to try to update to 5.0 to see if that fixes it

**Comment by atitpatel** [comment]
We are experiencing the same issue with very similar stack trace. This too is happening on lot of Android users we have. Here is the stack trace.


```

Newest

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
    at com.rnappauth.RNAppAuthModule.onActivityResult(RNAppAuthModule.java:492)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:334)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:824)
    at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:113)
    at expo.modules.ReactActivityDelegateWrapper.onActivityResult(ReactActivityDelegateWrapper.kt:145)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
    at android.app.Activity.dispatchActivityResult(Activity.java:8659)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=52, result=-1, data=Intent { dat=com.airbase.auth0://callback?code=HGiHfN21whrqGEHttdWpjZKPUyYrcbDqhgM8ILx6QWMPL&state=j4Cv2lC4LGK8NGPebA0j9Q (has extras) }} to activity {com.airbase/com.airbase.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5864)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)```
    
    
   Kindly help me out. We are using the latest version 6.4.3. Let me know if you need any more info. cc @Jay-A-McBee

**Comment by atitpatel** [comment]
Can this be related to Codepush in any way? We observed that this issue didn't report in a codepush-free version. When we again code-pushed a bundle, it came up. Though the number suggests that it is not happening to all the users. @Jay-A-McBee
