### ISSUE TITLE
Crash when attempting to deep link into app from login webview on android 

### ISSUE THREAD

**Issue by sattaman** [FormidableLabs/react-native-app-auth#94]
On my login page I have a register link, which redirects away from ID Server to a register page. On this page, I have a link into my app (using a different url to the one defined in appAuthredirectScheme) but that seems to be picked up by this library and cause a crash. 

```
04-12 15:18:41.976 9329-9329/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.myapp, PID: 9329
                                                 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {com.myapp/com.myapp.MainActivity}: java.lang.NullPointerException: dataIntent must not be null
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
                                                     at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                  Caused by: java.lang.NullPointerException: dataIntent must not be null
                                                     at net.openid.appauth.Preconditions.checkNotNull(Preconditions.java:55)
                                                     at net.openid.appauth.AuthorizationResponse.fromIntent(AuthorizationResponse.java:565)
                                                     at com.reactlibrary.RNAppAuthModule.onActivityResult(RNAppAuthModule.java:212)
                                                     at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:265)
                                                     at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:675)
                                                     at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
                                                     at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:7539)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532) 
                                                     at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by cavator** [comment]
i'm having this issue, and have no ideia how solve. i have a "callback" with is a .php file with nothing, i have no ideia what need to have in the redirectUrl.
i know is a simple issue, and with a easy resolution, but i'm new in that
so please don't make me questions like "send your whatever config from whatever command for see whatever log" i know is just something i didn't do in the call back and the doc say nothing about how and what have in the callback

**Comment by cavator** [comment]
now i literary did a only "<?php" file and i'm getting 
code:"Failed exchange token"
message:"client_id and client_secret required"
wtf, i'm sending this 2 infos in the "config" some one please and fast help me, i don't wanna loose my time in a stupid problem

**Comment by cavator** [comment]
ok, now i try a numerous files with whatever inside, and all i'm getting the client_id and secret, now i have no fucking ideia whats happing
